### PR TITLE
Add issue & pull request templates

### PR DESCRIPTION
**Pull request by chasenlehara**
Related to https://github.com/donejs/developer-relations/issues/15

### CODE REVIEW

**Comment by phillipskevin** [comment]
@chasenlehara do you want to just add this in major since the DoneJS 1.0 release is imminent and the tests will work over there?

**Comment by chasenlehara** [comment]
@phillipskevin Changed the base and AppVeyor is still failing. :/ I don’t see a way to restart the build. What’s the best next step?

**Comment by phillipskevin** [comment]
@chasenlehara I think the only way is to push a new commit... or amend your commit and force push.

**Comment by phillipskevin** [comment]
Appveyor says this is an npm bug: http://help.appveyor.com/discussions/problems/3147-error-eperm-operation-not-permitted-rename-on-npm-install

So we can either
- not use Node 4 anymore
- add a `--force` flag to our `npm install` in the appveyor file
- use `appveyor-retry`

I'm not sure why this is only happening to you now, @chasenlehara.

**Pull request merged**
