### PR TITLE
read "appName" and "folder" from package.json

### PR DESCRIPTION
**Pull request by pYr0x**
`this.fs.accessSync` is not a valid function, yeoman does't support all the functions from fs and fs-extra
@daffl @matthewp can you looked into it and merge?
after that the CI on donejs-cli should pass

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks for taking a look at this. I'll run the donejs-cli tests against this branch before merging.

**Comment by justinbmeyer** [comment]
I think similar changes need to be made in supermodel and the other generators?

**Comment by pYr0x** [comment]
@justinbmeyer you are right. i updated the supermap generator. 
the app generator doesnt need to be updated. do i miss something?

**Comment by pYr0x** [comment]
@daffl @matthewp can we merge this and update donejs/cli https://github.com/donejs/cli/pull/36 ?

**Pull request merged**
