### PR TITLE
Adding: Yarn Support for the generator

### PR DESCRIPTION
**Pull request by frank-dspeed**

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Thanks!  Any idea why this breaks in node .10?

**Comment by frank-dspeed** [comment]
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/fs-extra/-/fs-extra-0.26.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/donejs/-/donejs-0.9.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/coveralls-send/-/coveralls-send-0.0.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/donejs-cli/-/donejs-cli-0.8.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/mocha-lcov-reporter/-/mocha-lcov-reporter-1.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/lodash-inflection/-/lodash-inflection-1.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/fs-extra/-/fs-extra-0.26.7.tgz
npm ERR! fetch failed https://registry.npmjs.org/coveralls-send/-/coveralls-send-0.0.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/donejs-cli/-/donejs-cli-0.8.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash-inflection/-/lodash-inflection-1.4.1.tgz
npm ERR! Windows_NT 6.3.9600

it fails because it has problems fetching from npm i don't thin it it in general a problem i have tested the code realy well in my fork of donejs

**Comment by frank-dspeed** [comment]
Also Tell me pls i whant to move all donejs-cli init add parts to the generator if you aggree with this i have prepared a generator that can do all actions needed including creating a supplyed dir.

so you can run it even via yo donejs add app or yo donejs add or yo donejs add app dir or even absolute relativ dir.

also i moved in to the generator the donejs depdency specifications so that they are in a dir called versions and are choose able via the generator. so it don't depends on donejs-cli any more but can still be runned by donejs cli

**Comment by matthewp** [comment]
@frank-dspeed is the goal of that to avoiding using `donejs add .` directly?

**Comment by frank-dspeed** [comment]
@marshallswain this feature will still exist it will be linke npm -g install generator-feathers and it will be coded in the right way to add feathers to a existing project. the generators don't need to be attached to the project it self.

**Comment by frank-dspeed** [comment]
and to install generator-feathers you could use yo in the current project dir or else where it offers

```
? 'Allo Frank! What would you like to do? (Use arrow keys)
  Run a generator
❯ Donejs 
  Donejs2
  ──────────────
  Update your generators 
  Install a generator 
  Find some help 
(Move up and down to reveal more choices)
```

**Comment by marshallswain** [comment]
There's work in progress on adding yarn support directly into yeoman: https://github.com/yeoman/generator/pull/974

**Comment by frank-dspeed** [comment]
@marshallswain yes thats right but at present it will have no detection method at present it is choose able already via other methods.

I am thinking also havy on how to implament that.

I Have the following state:
donejs - bin should run in project dirs all aviable bins
donejs - bin add command should pass anything to the generator donejs (global version) if no local version exists! else use local version to don't brake anything.
add should also be the old init command and add app is a alias for add without arguments.
then we should put into the generator that if type is not plugin app init that he should try the old generate method.

so donejs bin is only a shortcut to local project node_modules/.bin and generator-donejs

**Comment by frank-dspeed** [comment]
And after all that we should split this generator into using generator-steal and generator-canjs and add extra options for configuring the both systems at present we role out a relativ static skeletton.

**Comment by frank-dspeed** [comment]
Only for documentation this pull is depricated in favor of npm init donejs-feathers or similar yarn init

**Comment by frank-dspeed** [comment]
This is deprecated in favor of yarn or npm init stealjs and feathersjs

**Pull request closed without merging**
