### PR TITLE
Speed up the DoneJS generators with yarn support

### PR DESCRIPTION
**Pull request by marshallswain**
I've added a simple utility to detect yarn and use it to install dependencies if it's installed.  This brings the install time down to 30 seconds when generating a new DoneJS app.

I haven't figured out a good way to test this.

### CODE REVIEW

**Comment by andrejewski** [comment]
NPM v5 looks to be more performant than Yarn so this PR may be best left unmerged.

**Comment by marshallswain** [comment]
@andrejewski when will it be available?

**Comment by andrejewski** [comment]
@marshallswain I'm unsure, but it is expected to be released before Node v8 so quite soon.

**Comment by andrejewski** [comment]
@marshallswain [npm@5 has been released](http://blog.npmjs.org/post/161081169345/v500)

**Comment by marshallswain** [comment]
It works!  yay!

**Pull request closed without merging**
