### PR TITLE
Add done-css as a plugin.

### LINKED ISSUE #170: done-css should be a listed plugin
@matthewp commented on [Thu Jan 12 2017](https://github.com/donejs/cli/issues/69)

### PR DESCRIPTION
**Pull request by matthewp**
Fixes #170

### CODE REVIEW

**Comment by phillipskevin** [comment]
These tests have been failing. I thought I had an issue for it, but I guess not. I'll open one now. Feel free to merge this.

**Comment by matthewp** [comment]
Ah ok. I'm taking a quick look either way.

**Comment by phillipskevin** [comment]
Here's the issue in case you figure it out: https://github.com/donejs/generator-donejs/issues/172.

Might just be really slow?

**Comment by matthewp** [comment]
My first thought is Firefox version. Going to try updating to latest here.

**Comment by phillipskevin** [comment]
That's probably it...

**Pull request merged**
