### PR TITLE
113 hashchange routing

### PR DESCRIPTION
**Pull request by ilyavf**
Fixed issue from DoneJS [Make development.html use hashchange routing](https://github.com/donejs/donejs/issues/609). Added a test.

To fix is to map pushstate into empty in development.html template.

### CODE REVIEW

**Comment by marshallswain** [comment]
Isn't this ready to be merged?

**Comment by marshallswain** [comment]
Actually, this doesn't seem to work in DoneJS@0.10.0-pre.1.

**Comment by phillipskevin** [comment]
@ilyavf can you change this to point to `major` so we can get it into 1.0?

**Comment by phillipskevin** [comment]
Also, it will need to map `can-route-pushstate` to empty instead of `can/route/pushstate/pushstate`.

**Comment by phillipskevin** [comment]
Thanks @ilyavf for doing this. I'm sure it took a lot of work to get these tests working.

These changes are made in the `major` branch and I don't think we're going to update the 0.9 generators with this change, so I'm going to close this PR. If you feel like we really should update 0.9 for this, please re-open and we can discuss.

**Pull request closed without merging**
