### PR TITLE
Fix 509 generate plural fixture names

### PR DESCRIPTION
**Pull request by cherifGsoul**
this implements https://github.com/donejs/donejs/issues/509

### CODE REVIEW

**Comment by cherifGsoul** [comment]
@matthewp can you see if this is ok?

**Comment by justinbmeyer** [comment]
The output from appveyor.

```
> generator-donejs@0.9.1 test C:\projects\generator-donejs
> mocha test/ --timeout 600000
 
 
 
  generator-donejs
    donejs:app
[?25hnpm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--loglevel" "error" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
 
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--loglevel" "error" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
 
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--loglevel" "error" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
 
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
 
```

**Comment by matthewp** [comment]
I'm betting npm was just down at the moment, will rerun it.  We should avoid tests that need to use networking, I understand why this one exists though.

**Comment by matthewp** [comment]
Awesome, it passed, we can talk about it in the standup tomorrow. Not sure if this is a "breaking" change or not, since we are changing what is output.

**Comment by cherifGsoul** [comment]
Ok, thank you @matthewp

**Pull request merged**
