### PR TITLE
Fix generated default/index.js file

### PR DESCRIPTION
**Pull request by chasenlehara**
After running `donejs add generator` in a new folder, running `npm test` did not work; the tests would just timeout.

The cause of this issue was a callback being passed to `prompt` instead of using the promise that it returns.

With this change, the tests successfully complete in a new project.

Tests before:
screen shot 2016-05-22 at 4 07 57 pm

Tests after:
screen shot 2016-05-22 at 3 58 08 pm

### CODE REVIEW

**Comment by matthewp** [comment]
This is the root issue: https://github.com/donejs/generator-donejs/blob/0c9d6e0ccf73b6f816d203d83665253676e97647/generator/index.js#L106-L107

This will always install latest. We should use semver ranges.  I wonder where we can put those?

**Comment by chasenlehara** [comment]
I’m guessing we can tack on the version, something like `yeoman-generator@0.20.x`

**Comment by matthewp** [comment]
I meant where do we put this information, I don't want to put it directly in the file. I think for now I'll create a module called "packages" that looks like:

```js
module.exports = {
  devDependencies: {
    "yeoman-foo": "^1.0.0"
    ...
  }
};
```

**Comment by matthewp** [comment]
Closing in favor of the issue: https://github.com/donejs/generator-donejs/issues/130

**Pull request closed without merging**
